name: Docker Build and Push

on:
  schedule:
    - cron: '0 16 * * *'  # UTC 16:00 = 北京时间 00:00
  workflow_dispatch:  # 支持手动触发
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-build.yml'

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE: your-dockerhub-username/p115nano302
  PACKAGE_NAME: p115nano302

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests packaging

      - name: Check PyPI version
        id: check_version
        run: |
          VERSION=$(python scripts/check_version.py ${{ env.PACKAGE_NAME }})
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Current PyPI version: $VERSION"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./p115nano302
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ steps.check_version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDTIME=${{ github.event.repository.updated_at }} 
